server:    
    port: 80
    session:
        timeout: 1800
spring: 
  datasource:   
    url: jdbc:h2:mem:activiti;DB_CLOSE_DELAY=1000
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: default  
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy